web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
web: nodemon ../bin/www
